Achievement:
    type: entity
    table: achievement
    id:
        idAch:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: id_ach
            generator:
                strategy: IDENTITY
    fields:
        nomAch:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: nom_ach
        descriptionAch:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: description_ach
    lifecycleCallbacks: {  }
